/* ============================================================
   NarrativePanel — AI-generated scenario narrative & recommendations
   ============================================================ */

import { Sparkles, ChevronDown, ChevronUp, Copy, CheckCheck } from 'lucide-react';
import { useState } from 'react';

const DEMO_NARRATIVE = {
  summary: 'Based on your scenario configuration (Port Closure — Asia Pacific, Severity 70, Duration 14 days), our simulation has identified significant downstream impacts across 127 shipments with a combined value of $4.2M at risk.',
  highlights: [
    '🔴 Alternative Route A (Cape of Good Hope) reduces risk by 62% but adds 14 days and $1,400/TEU in cost.',
    '🟡 12 critical shipments containing pharmaceuticals require priority rerouting within 48 hours.',
    '🟢 Co-loading opportunities identified at Hamburg that could offset $280K of additional freight cost.',
  ],
  recommendations: [
    { priority: 'Immediate', action: 'Reroute SHP-01003, SHP-01009, SHP-01021 via Alternative A', reasoning: 'Medical supply chain, customer SLA breach risk.' },
    { priority: 'Within 48h', action: 'Notify 34 shippers of expected 12–16 day delay', reasoning: 'Proactive communication reduces claim exposure.' },
    { priority: 'This week', action: 'Lock in capacity on Alternative B for remaining cargo', reasoning: 'Rates likely to surge 20–30% within 5 days.' },
  ],
};

/**
 * @param {object} props
 * @param {object} [props.narrative]
 * @param {boolean} [props.hasResults]
 */
export default function NarrativePanel({ narrative = DEMO_NARRATIVE, hasResults = true }) {
  const [expanded, setExpanded] = useState(true);
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = [
      narrative.summary,
      '\nHighlights:',
      ...narrative.highlights,
      '\nRecommendations:',
      ...narrative.recommendations.map((r) => `[${r.priority}] ${r.action}`),
    ].join('\n');

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available
    }
  };

  return (
    <div className="narrative-panel-card" role="region" aria-label="AI scenario narrative">
      {/* Header */}
      <div className="card-header">
        <div className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Sparkles size={15} color="var(--color-accent-secondary)" aria-hidden="true" />
          AI Scenario Narrative
        </div>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            className="btn btn-ghost btn-sm"
            onClick={handleCopy}
            aria-label="Copy narrative to clipboard"
            disabled={!hasResults}
          >
            {copied ? <CheckCheck size={13} color="var(--color-risk-low)" /> : <Copy size={13} />}
          </button>
          <button
            className="btn btn-ghost btn-sm"
            onClick={() => setExpanded(!expanded)}
            aria-label={expanded ? 'Collapse narrative' : 'Expand narrative'}
            aria-expanded={expanded}
          >
            {expanded ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
          </button>
        </div>
      </div>

      {expanded && (
        <div
          className="narrative-content"
          style={{
            opacity: hasResults ? 1 : 0.4,
            filter: hasResults ? 'none' : 'blur(3px)',
            transition: 'all 0.4s ease',
            pointerEvents: hasResults ? 'auto' : 'none',
          }}
        >
          {/* AI badge */}
          <div className="narrative-ai-badge" aria-label="Generated by AI">
            <Sparkles size={9} aria-hidden="true" />
            AI-generated · GPT-4o
          </div>

          {/* Summary */}
          <p style={{ fontSize: 'var(--text-sm)', lineHeight: 1.7, color: 'var(--color-text-secondary)', marginBottom: '12px' }}>
            {narrative.summary}
          </p>

          {/* Key highlights */}
          <div style={{ marginBottom: '16px' }}>
            <div style={{ fontSize: 'var(--text-xs)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'var(--color-text-muted)', marginBottom: '8px' }}>
              Key Findings
            </div>
            {narrative.highlights.map((h, i) => (
              <div key={i} className="narrative-highlight">
                {h}
              </div>
            ))}
          </div>

          {/* Recommendations */}
          <div>
            <div style={{ fontSize: 'var(--text-xs)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'var(--color-text-muted)', marginBottom: '8px' }}>
              Recommended Actions
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {narrative.recommendations.map((rec, i) => {
                const priorityColors = { Immediate: '#ef4444', 'Within 48h': '#f97316', 'This week': '#eab308' };
                const color = priorityColors[rec.priority] || '#6b7280';
                return (
                  <div key={i} style={{
                    display: 'flex', gap: '10px',
                    padding: '10px', borderRadius: 'var(--radius-md)',
                    background: `${color}0d`, border: `1px solid ${color}22`,
                  }}>
                    <span style={{
                      flexShrink: 0, fontSize: '10px', fontWeight: 700,
                      color, padding: '2px 6px',
                      background: `${color}1a`, borderRadius: '4px',
                      height: 'fit-content', whiteSpace: 'nowrap',
                    }}>
                      {rec.priority}
                    </span>
                    <div>
                      <div style={{ fontSize: 'var(--text-xs)', fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: '3px' }}>
                        {rec.action}
                      </div>
                      <div style={{ fontSize: '11px', color: 'var(--color-text-muted)', lineHeight: 1.4 }}>
                        {rec.reasoning}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {!hasResults && (
        <div style={{ padding: '24px', textAlign: 'center', color: 'var(--color-text-muted)', fontSize: 'var(--text-sm)' }}>
          Run the simulation to generate AI narrative
        </div>
      )}
    </div>
  );
}
